### ISSUE TITLE
TabError in monitor()

### ISSUE THREAD

**Issue by thecodingchicken** [adityashrm21/Network-Usage-Tracker#1]
File "bandwidth.py", line 15
    output=proc.communicate()
                            ^
TabError: inconsistent use of tabs and spaces in indentation

When this function is run, it creates a TabError.
Entering it line by line in IDLE works, but the indentation doesn't work in this case.

**Comment by adityashrm21** [comment]
I have corrected the issue. Check and let me know if it works for you.
